title: Minescript Sample
description: Minescript Sample
theme: just-the-docs

url: https://sam-ple.github.io/minescript-sample

# Aux links for the upper right navigation
aux_links:
  "Minescript Sample on GitHub":
    - "https://github.com/sam-ple/minescript-sample"

# External navigation links
nav_external_links:
  - title: Minescript Sample on GitHub
    url: https://github.com/sam-ple/minescript-sample

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/sam-ple/minescript-sample" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
